const express      =  require('express');
const bodyParser   =  require('body-parser');
const indexRouter   =  require('./routes/index');
const port = process.env.port || 6001;
const app  = express();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
app.use('/', indexRouter);
app.listen(port);
module.exports = { app };